# Generated by Django 2.0 on 2019-02-26 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=7), django.core.validators.MinValueValidator(limit_value=0.01, message='The base amount has to be greater than 0.00')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('G', 'Grams'), ('KG', 'Kilograms'), ('CL', 'Centiliters'), ('LT', 'Liters')], max_length=5, validators=[django.core.validators.MaxLengthValidator(limit_value=5, message='The unit abbreviation must be 5 characters maximum.'), django.core.validators.MinLengthValidator(limit_value=1, message='The unit abbreviation must be 1 character minimum.')]),
        ),
    ]
