# Generated by Django 2.0 on 2019-02-26 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20190226_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='article_number',
            field=models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(limit_value=64, message='The name of the article must be 5 characters maximum.'), django.core.validators.MinLengthValidator(limit_value=1, message='The name of the article must be 1 character minimum.')]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=7), django.core.validators.MinValueValidator(limit_value=0.01, message='The base price has to be greater than 0.00')]),
        ),
    ]
