# Generated by Django 2.0 on 2019-02-26 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20190226_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='', max_length=64, validators=[django.core.validators.MaxLengthValidator(limit_value=64, message='The name of the article must be 5 characters maximum.'), django.core.validators.MinLengthValidator(limit_value=1, message='The name of the article must be 1 character minimum.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='article_number',
            field=models.CharField(max_length=5, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=5, message='The article number must be 5 characters maximum.'), django.core.validators.MinLengthValidator(limit_value=1, message='The article number must be 1 character minimum.')]),
        ),
    ]
