# Generated by Django 2.0 on 2019-02-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20190226_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-last_modified']},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
