# Generated by Django 2.0 on 2019-02-27 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_auto_20190227_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(limit_value=64, message='The name of the article must be 64 characters maximum.'), django.core.validators.MinLengthValidator(limit_value=1, message='The name of the article must be 1 character minimum.')]),
        ),
    ]
