version: '3'

services:
    db:
        image: postgres
    migration:
        build: .
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
    web:
        build: .
        command: python manage.py runserver
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
            - migration
