# Generated by Django 2.0 on 2019-02-27 17:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0007_auto_20190227_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientOfRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.DecimalValidator(decimal_places=2, max_digits=7), django.core.validators.MinValueValidator(limit_value=0.01, message='The quantity has to be greater than 0.00')])),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(limit_value=64, message='The name of the recipe must be 5 characters maximum.'), django.core.validators.MinLengthValidator(limit_value=1, message='The name of the recipe must be 1 character minimum.')])),
                ('description', models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(limit_value=64, message='The description of the recipe must be 64 characters maximum.'), django.core.validators.MinLengthValidator(limit_value=1, message='The description of the recipe must be 1 character minimum.')])),
                ('method_of_preparation', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=1, message='The  method of preparation field of the recipe cannot be empty.')])),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_modified', '-date_created'],
            },
        ),
        migrations.AddField(
            model_name='ingredientofrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.Recipe'),
        ),
    ]
